{
 "title": "Internet quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Latency distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ping_seconds", "legendFormat": "quantile: {{quantile}}" }
   ]
  },
  {
   "title": "Percentile latencies",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Average ping time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ping_seconds_sum[30s]) / rate(ping_seconds_count[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ping drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(ping_failed_count[30s])\n", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}